### ISSUE TITLE
GPG Issue

### ISSUE THREAD

**Issue by hakunin** [newmen/ansible-rvm#5]
Hi, my machine was missing GPG, which is a dependency to install rvm.

Adding gnu this to the role solved my issue.

```
  - name: ensure necessary packages are installed
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - curl
      - gnupg2
```
